pool:
  vmImage: 'windows-latest'

jobs:
  - job: CdForOIDCProviderNest
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: 'github.com,140.82.112.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
          sshKeySecureFile: 'id_rsa'
      - task: NodeTool@0
        inputs:
          versionSpec: '12.18'
        displayName: 'Install Node.js'
      - task: Cache@2
        inputs:
          key: 'npm | "$(Agent.OS)" | package-lock.json'
          restoreKeys: 'npm | "$(Agent.OS)" | package-lock.json'
          path: $(npm_config_cache)
        displayName: Cache NPM

      - script: npm install -g @angular/cli
        displayName: NPM Install Angular CLI

      - script: |
          npx nx run ues-effluent-angular:build --prod --baseHref /effluent/
        displayName: 'Build OIDC-Admin-Angular'

      - task: CopyFiles@2
        inputs:
          Contents: 'dist/**' # Pull the build directory (React)
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Copy Distribution Files'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
          ArtifactName: 'www' # output artifact named www
        displayName: 'Publish Artifacts'
